variables:
  TEENSY3_CROSSFILE_GCC: cross-teensy3-gcc.txt
  TEENSYLC_CROSSFILE_GCC: cross-teensylc-gcc.txt
  INSTALL_PREFIX: $CI_PROJECT_DIR/install

.build:
  stage: build
  image: registry.gitlab.com/kjerstadius/docker-gcc-arm-none-eabi-meson/gcc-arm-none-eabi-meson
  script:
    - meson $BUILD_DIR
        -Dvariant=$VARIANT
        -Dcpu_frequency=$CPU_FREQ
        -Dprefix=$INSTALL_PREFIX
        --cross-file=$CROSS_FILE
    - meson configure $BUILD_DIR
    - ninja -C $BUILD_DIR install
    - ninja -C $BUILD_DIR blinky.size
  artifacts:
    paths:
      - $INSTALL_PREFIX/

Teensy 3.0:
  extends: .build
  variables:
    BUILD_DIR: build
    CPU_FREQ: '72'
    CROSS_FILE: $TEENSY3_CROSSFILE_GCC
    VARIANT: '3.0'

Teensy 3.2:
  extends: .build
  variables:
    BUILD_DIR: build-teensy32
    CPU_FREQ: '96'
    CROSS_FILE: $TEENSY3_CROSSFILE_GCC
    VARIANT: '3.2'

Teensy 3.5:
  extends: .build
  variables:
    BUILD_DIR: build-teensy35
    CPU_FREQ: '120'
    CROSS_FILE: $TEENSY3_CROSSFILE_GCC
    VARIANT: '3.5'

Teensy 3.6:
  extends: .build
  variables:
    BUILD_DIR: build-teensy36
    CPU_FREQ: '168'
    CROSS_FILE: $TEENSY3_CROSSFILE_GCC
    VARIANT: '3.6'

Teensy LC:
  extends: .build
  variables:
    BUILD_DIR: build-teensyLC
    CROSS_FILE: $TEENSYLC_CROSSFILE_GCC
    CPU_FREQ: '48'
    VARIANT: LC
